name: Deploy Task Management API

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          
      - name: Add server to known hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan 54.205.127.134 >> ~/.ssh/known_hosts
          
      - name: Deploy to EC2
        run: |
          ssh ubuntu@54.205.127.134 "if [ ! -d ~/Task-management-LLM-API ]; then git clone https://github.com/hsn07pk/Task-management-LLM-API.git ~/Task-management-LLM-API; fi && cd ~/Task-management-LLM-API && git fetch && git checkout ${GITHUB_REF_NAME} && docker-compose down && docker-compose up -d --build"
