name: Deploy Task Management API

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  # test:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2
  #     - name: Set up Python
  #       uses: actions/setup-python@v2
  #       with:
  #         python-version: '3.9'
  #     - name: Install dependencies
  #       run: |
  #         python -m pip install --upgrade pip
  #         pip install -r requirements.txt
  #         pip install -r requirements-test.txt
  #     - name: Run tests
  #       run: |
  #         pytest --html=reports/report.html --self-contained-html

  deploy:
    # needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          
      - name: Add server to known hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan ${{ secrets.EC2_IP }} >> ~/.ssh/known_hosts
          
      - name: Deploy to EC2
        run: |
          ssh ubuntu@${{ secrets.EC2_IP }} "cd ~/Task-management-LLM-API && git pull && docker-compose down && docker-compose up -d --build"