name: Deploy Task Management API

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
             
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
                 
      - name: Add server to known hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan ${{ secrets.EC2_IP }} >> ~/.ssh/known_hosts
                 
      - name: Deploy to EC2 with environment setup
        run: |
          ssh ubuntu@${{ secrets.EC2_IP }} "if [ ! -d ~/Task-management-LLM-API ]; then git clone https://github.com/hsn07pk/Task-management-LLM-API.git ~/Task-management-LLM-API; fi && cd ~/Task-management-LLM-API && git fetch && git checkout ${GITHUB_REF_NAME} && echo 'DB_USER=admin' > .env && echo 'DB_PASSWORD=helloworld123' >> .env && echo 'DB_NAME=task_management_db' >> .env && echo 'JWT_SECRET_KEY=your-secure-key' >> .env && echo 'FLASK_ENV=production' >> .env && docker-compose down && docker volume rm task-management-llm-api_postgres_data || true && docker-compose up -d --build"